In [1]:
# Creating dummy dataset
import pandas as pd
import numpy as np
from random import choices

In [2]:
np.random.seed(10)  # For reproducibility

In [3]:
num_records = 1000
num_outlets = 10
num_products = 20

In [4]:
# 2 Quarters (Jan - March, Apr - June)
dates = pd.date_range(start='2023-01-01', end = '2023-06-30')

dates = choices(dates, k=num_records)


In [5]:
len(dates)

1000

In [6]:
outlets = ['Outlet_' + str(i+1) for i in range(num_outlets)]
outlets = choices(outlets, k=num_records)

In [7]:
len(outlets)

1000

In [8]:
products = ['Product_' + str(i+1) for i in range(num_products)]
products = choices(products, k=num_records)

In [9]:
len(products)

1000

In [10]:
len(products)

1000

In [11]:
units_sold = np.random.randint(1, 200, size=num_records)
price_by_unit = np.random.uniform(10, 500, size=num_records)

In [12]:
units_sold

array([ 10, 126,  16,  65, 114, 124, 157, 158, 114,   9,  74,   1,  41,
       165, 116,  17, 101, 140,  55,  89, 108, 123,  63,  34, 101, 178,
       180,  55,  78, 198,  14, 154, 127, 142,  93,  87,  31, 159,  90,
       141,  66,  32,  58,  37,  28,  19,  94,  78, 151, 152,  95, 140,
       157,  75, 138,  16,  19, 119,  72,  89, 140, 146, 175, 136,  29,
        34,  97,  45, 134,   5,  72,  89,  89,  51, 109, 183,  35, 105,
        16,  89, 144, 135,  86, 151,  12, 113,  13,  63, 186,  80, 109,
        43,  58,  98,  51,  46, 169, 166, 129, 147,  24,   4,  30,  17,
        85,  83, 113,  15,  52,  80,  18, 179,  54, 154, 111, 177,  18,
       161,  82,  42,  91,  13,  31, 146, 145, 129, 160, 102, 193, 125,
       167,  23,  97,  67,  68, 191,  96, 100, 156,  83,  63,  78, 108,
        49, 118, 116, 166,  12, 150, 162,  96, 172,  74, 169, 102, 172,
        91,  72, 137,  73, 157, 110,  31, 124, 154, 191,  14, 170, 162,
         5,  95,  29,  40,  92, 104,  10,   8, 151,  33,   4,  1

In [13]:
price_by_unit

array([ 27.20453847, 195.40800841, 185.39125473, 137.19114478,
       304.34382759, 365.29842245, 203.37613901, 263.64931928,
       438.94845595, 139.02456451, 378.59563253, 135.60853023,
       361.18913023, 444.86477481, 374.32323295, 262.39544278,
        27.19501281, 386.45709082,  39.92585532, 433.81718673,
        77.37080758, 366.69069085, 307.68270008, 337.12364504,
        77.94005162, 261.62922049, 412.26145091, 162.41416698,
       435.50773063, 157.25767388, 223.42465465, 188.49730229,
       398.92689004, 489.42433087, 384.99669253, 485.54512237,
       120.26271073, 436.60254659, 205.80980569,  86.54620808,
       305.76766095, 304.71888035, 263.17976577, 463.42585842,
       352.62280704, 447.50828665, 487.9846315 , 257.99477395,
       468.94726186, 249.25023988, 227.04695034,  21.42210814,
        72.92995313, 357.24392381, 442.70121206,  33.24675991,
       224.63180956,  65.74277056,  88.91066701, 305.1426025 ,
       490.66022858, 287.53739625,  65.888844  , 266.84

In [14]:
total_sales = units_sold * price_by_unit

In [15]:
total_sales

array([2.72045385e+02, 2.46214091e+04, 2.96626008e+03, 8.91742441e+03,
       3.46951963e+04, 4.52970044e+04, 3.19300538e+04, 4.16565924e+04,
       5.00401240e+04, 1.25122108e+03, 2.80160768e+04, 1.35608530e+02,
       1.48087543e+04, 7.34026878e+04, 4.34214950e+04, 4.46072253e+03,
       2.74669629e+03, 5.41039927e+04, 2.19592204e+03, 3.86097296e+04,
       8.35604722e+03, 4.51029550e+04, 1.93840101e+04, 1.14622039e+04,
       7.87194521e+03, 4.65700012e+04, 7.42070612e+04, 8.93277918e+03,
       3.39696030e+04, 3.11370194e+04, 3.12794517e+03, 2.90285846e+04,
       5.06637150e+04, 6.94982550e+04, 3.58046924e+04, 4.22424256e+04,
       3.72814403e+03, 6.94198049e+04, 1.85228825e+04, 1.22030153e+04,
       2.01806656e+04, 9.75100417e+03, 1.52644264e+04, 1.71467568e+04,
       9.87343860e+03, 8.50265745e+03, 4.58705554e+04, 2.01235924e+04,
       7.08110365e+04, 3.78860365e+04, 2.15694603e+04, 2.99909514e+03,
       1.14500026e+04, 2.67932943e+04, 6.10927673e+04, 5.31948159e+02,
      

In [16]:
len(total_sales)

1000

In [17]:
df = pd.DataFrame({
    'Date': dates,
    'Outlet': outlets,
    'Product': products,
    'Units_Sold': units_sold,
    'Price_Per_Unit': price_by_unit,
    'Total_Sales': total_sales
})

In [18]:
df

,Date,Outlet,Product,Units_Sold,Price_Per_Unit,Total_Sales
0,2023-01-21,Outlet_2,Product_18,10,27.204538,272.045385
1,2023-04-01,Outlet_2,Product_1,126,195.408008,24621.409060
2,2023-06-21,Outlet_7,Product_8,16,185.391255,2966.260076
3,2023-01-30,Outlet_1,Product_5,65,137.191145,8917.424411
4,2023-05-31,Outlet_1,Product_14,114,304.343828,34695.196345
...,...,...,...,...,...,...
995,2023-06-10,Outlet_7,Product_20,37,19.028276,704.046201
996,2023-01-04,Outlet_7,Product_10,91,372.000914,33852.083211
997,2023-06-01,Outlet_1,Product_11,148,37.062541,5485.256005
998,2023-06-22,Outlet_10,Product_20,33,289.563788,9555.605018


In [19]:
import pandasai as pai
from pandasai_openai import AzureOpenAI

In [20]:
from dotenv import load_dotenv
import os

os.environ['AZURE_OPENAI_ENDPOINT'] = os.getenv('AZURE_OPENAI_ENDPOINT')
os.environ['AZURE_OPENAI_API_KEY'] = os.getenv('AZURE_OPENAI_API_KEY')
os.environ['AZURE_OPENAI_DEPLOYMENT_NAME'] = os.getenv('AZURE_OPENAI_DEPLOYMENT_NAME')

In [24]:
import os
from pandasai_openai import AzureOpenAI
import pandasai as pai

llm = AzureOpenAI(
    api_token=os.getenv('AZURE_OPENAI_API_KEY'),
    azure_endpoint=os.getenv('AZURE_OPENAI_ENDPOINT'),
    deployment_name=os.getenv('AZURE_OPENAI_DEPLOYMENT_NAME'),
    api_version="2024-02-01"
)

pai.config.set({"llm": llm})